#pragma once

#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
#define DYNAMIC_MACRO_NO_NESTING
#define KEY_OVERRIDE_REPEAT_DELAY 200
#define NO_ACTION_ONESHOT
#define TAP_CODE_DELAY 5
#define TAPPING_TERM 200
#define TAPPING_TOGGLE 3
#define UNICODE_CYCLE_PERSIST false
#define UNICODE_SELECTED_MODES UNICODE_MODE_WINCOMPOSE, UNICODE_MODE_LINUX
#define USB_POLLING_INTERVAL_MS 1
